export interface APIGatewayAPIKey {
    resource: Resource[];
}

export interface Resource {
    api_gateway_api_key: APIGatewayAPIKeyClass;
}

export interface APIGatewayAPIKeyClass {
    /** (Required) Name of the API key. */
    name:         any;
    /** (Required) An Amazon Web Services Marketplace customer identifier, when integrating with the Amazon Web Services SaaS Marketplace. */
    customer_id:  any;
    /** (Optional) API key description. Defaults to "Managed by Terraform". */
    description?: any;
    /** (Optional) Whether the API key can be used by callers. Defaults to `true`. */
    enabled?:     any;
    /** (Optional) Value of the API key. If specified, the value must be an alphanumeric string between 20 and 128 characters. If not specified, it will be automatically generated by AWS on creation. */
    value?:       any;
    /** (Optional) Key-value map of resource tags. If configured with a provider [`default_tags` configuration block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) present, tags with matching keys will overwrite those defined at the provider-level. */
    tags?:        any;
}