export interface CloudfrontPublicKey {
    resource: Resource[];
}

export interface Resource {
    cloudfront_public_key: CloudfrontPublicKeyClass;
}

export interface CloudfrontPublicKeyClass {
    /** (Optional) An optional comment about the public key. */
    comment?:     any;
    /** (Required) The encoded public key that you want to add to CloudFront to use with features like field-level encryption. */
    encoded_key:  any;
    /** (Optional) The name for the public key. By default generated by Terraform. */
    name?:        any;
    /** (Optional) The name for the public key. Conflicts with `name`. */
    name_prefix?: any;
}