export interface CloudwatchEventAPIDestination {
    resource: Resource[];
}

export interface Resource {
    cloudwatch_event_api_destination: CloudwatchEventAPIDestinationClass;
}

export interface CloudwatchEventAPIDestinationClass {
    /** (Required) The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_. */
    name:                              any;
    /** (Optional) The description of the new API Destination. Maximum of 512 characters. */
    description?:                      any;
    /** (Required) URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include "*" as path parameters wildcards to be set from the Target HttpParameters. */
    invocation_endpoint:               any;
    /** (Required) Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc. */
    http_method:                       any;
    /** (Optional) Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300). */
    invocation_rate_limit_per_second?: any;
    /** (Required) ARN of the EventBridge Connection to use for the API Destination. */
    connection_arn:                    any;
}