export interface EmrSecurityConfiguration {
    resource: Resource[];
}

export interface Resource {
    emr_security_configuration: EmrSecurityConfigurationClass;
}

export interface EmrSecurityConfigurationClass {
    /** (Optional) The name of the EMR Security Configuration. By default generated by Terraform. */
    name?:         any;
    /** (Optional) Creates a unique name beginning with the specified */
    name_prefix?:  any;
    /** (Required) A JSON formatted Security Configuration */
    configuration: any;
}