export interface NeptuneEventSubscription {
    resource: Resource[];
}

export interface Resource {
    neptune_event_subscription: NeptuneEventSubscriptionClass;
}

export interface NeptuneEventSubscriptionClass {
    /** (Optional) A boolean flag to enable/disable the subscription. Defaults to true. */
    enabled?:          any;
    /** (Optional) A list of event categories for a `source_type` that you want to subscribe to. Run `aws neptune describe-event-categories` to find all the event categories. */
    event_categories?: any;
    /** (Optional) The name of the Neptune event subscription. By default generated by Terraform. */
    name?:             any;
    /** (Optional) The name of the Neptune event subscription. Conflicts with `name`. */
    name_prefix?:      any;
    /** (Required) The ARN of the SNS topic to send events to. */
    sns_topic_arn:     any;
    /** (Optional) A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a `source_type` must also be specified. */
    source_ids?:       any;
    /** (Optional) The type of source that will be generating the events. Valid options are `db-instance`, `db-security-group`, `db-parameter-group`, `db-snapshot`, `db-cluster` or `db-cluster-snapshot`. If not set, all sources will be subscribed to. */
    source_type?:      any;
    /** (Optional) A map of tags to assign to the resource. If configured with a provider [`default_tags` configuration block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) present, tags with matching keys will overwrite those defined at the provider-level. */
    tags?:             any;
}