export interface SagemakerUserProfile {
    resource: Resource[];
}

export interface Resource {
    sagemaker_user_profile: SagemakerUserProfileClass;
}

export interface SagemakerUserProfileClass {
    /** (Required) The name for the User Profile. */
    user_profile_name:                      any;
    /** (Required) The ID of the associated Domain. */
    domain_id:                              any;
    /** (Optional) A specifier for the type of value specified in `single_sign_on_user_value`. Currently, the only supported value is `UserName`. If the Domain's AuthMode is SSO, this field is required. If the Domain's AuthMode is not SSO, this field cannot be specified. */
    single_sign_on_user_identifier?:        any;
    /** (Required) The username of the associated AWS Single Sign-On User for this User Profile. If the Domain's AuthMode is SSO, this field is required, and must match a valid username of a user in your directory. If the Domain's AuthMode is not SSO, this field cannot be specified. */
    single_sign_on_user_value:              any;
    /** (Required) The user settings. See [User Settings](#user-settings) below. */
    user_settings:                          any;
    /** (Optional) A map of tags to assign to the resource. If configured with a provider [`default_tags` configuration block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) present, tags with matching keys will overwrite those defined at the provider-level. */
    tags?:                                  any;
    /** (Required) The execution role ARN for the user. */
    execution_role:                         any;
    /** (Optional) The security groups. */
    security_groups?:                       any;
    /** (Optional) The sharing settings. See [Sharing Settings](#sharing-settings) below. */
    sharing_settings?:                      any;
    /** (Optional) The TensorBoard app settings. See [TensorBoard App Settings](#tensorboard-app-settings) below. */
    tensor_board_app_settings?:             any;
    /** (Optional) The Jupyter server's app settings. See [Jupyter Server App Settings](#jupyter-server-app-settings) below. */
    jupyter_server_app_settings?:           any;
    /** (Optional) The kernel gateway app settings. See [Kernel Gateway App Settings](#kernel-gateway-app-settings) below. */
    kernel_gateway_app_settings?:           any;
    /** (Optional) The RSession app settings. See [RSession App Settings](#rsession-app-settings) below. */
    r_session_app_settings?:                any;
    /** (Optional) A collection of settings that configure user interaction with the RStudioServerPro app. See [RStudio Server Pro App Settings](#rstudio-server-pro-app-settings) below. */
    r_studio_server_pro_app_settings?:      any;
    /** (Optional) The Canvas app settings. See [Canvas App Settings](#canvas-app-settings) below. */
    canvas_app_settings?:                   any;
    /** (Optional) The model registry settings for the SageMaker Canvas application. See [Model Register Settings](#model-register-settings) below. */
    model_register_settings?:               any;
    /** (Optional) Time series forecast settings for the Canvas app. see [Time Series Forecasting Settings](#time-series-forecasting-settings) below. */
    time_series_forecasting_settings?:      any;
    /** (Optional) The workspace settings for the SageMaker Canvas application. See [Workspace Settings](#workspace-settings) below. */
    workspace_settings?:                    any;
    /** (Optional) Whether to include the notebook cell output when sharing the notebook. The default is `Disabled`. Valid values are `Allowed` and `Disabled`. */
    notebook_output_option?:                any;
    /** (Optional) The Amazon Web Services Key Management Service (KMS) encryption key ID that is used to encrypt artifacts generated by Canvas in the Amazon S3 bucket. */
    s3_kms_key_id?:                         any;
    /** (Optional) When `notebook_output_option` is Allowed, the Amazon S3 bucket used to save the notebook cell output. */
    s3_output_path?:                        any;
    /** (Optional) The default instance type and the Amazon Resource Name (ARN) of the SageMaker image created on the instance. see [Default Resource Spec](#default-resource-spec) below. */
    default_resource_spec?:                 any;
    /** (Optional) A list of custom SageMaker images that are configured to run as a KernelGateway app. see [Custom Image](#custom-image) below. */
    custom_image?:                          any;
    /** (Optional) The Amazon Resource Name (ARN) of the Lifecycle Configurations. */
    lifecycle_config_arns?:                 any;
    /** (Optional) A list of Git repositories that SageMaker automatically displays to users for cloning in the JupyterServer application. see [Code Repository](#code-repository) below. */
    code_repository?:                       any;
    /** (Optional) Indicates whether the current user has access to the RStudioServerPro app. Valid values are `ENABLED` and `DISABLED`. */
    access_status?:                         any;
    /** (Optional) The level of permissions that the user has within the RStudioServerPro app. This value defaults to `R_STUDIO_USER`. The `R_STUDIO_ADMIN` value allows the user access to the RStudio Administrative Dashboard. Valid values are `R_STUDIO_USER` and `R_STUDIO_ADMIN`. */
    user_group?:                            any;
    /** (Optional) The URL of the Git repository. */
    repository_url?:                        any;
    /** (Optional) The instance type. */
    instance_type?:                         any;
    /** (Optional) The Amazon Resource Name (ARN) of the Lifecycle Configuration attached to the Resource. */
    lifecycle_config_arn?:                  any;
    /** (Optional) The Amazon Resource Name (ARN) of the SageMaker image created on the instance. */
    sagemaker_image_arn?:                   any;
    /** (Optional) The ARN of the image version created on the instance. */
    sagemaker_image_version_arn?:           any;
    /** (Required) The name of the App Image Config. */
    app_image_config_name:                  any;
    /** (Required) The name of the Custom Image. */
    image_name:                             any;
    /** (Optional) The version number of the Custom Image. */
    image_version_number?:                  any;
    /** (Optional)  The IAM role that Canvas passes to Amazon Forecast for time series forecasting. By default, Canvas uses the execution role specified in the UserProfile that launches the Canvas app. If an execution role is not specified in the UserProfile, Canvas uses the execution role specified in the Domain that owns the UserProfile. To allow time series forecasting, this IAM role should have the [AmazonSageMakerCanvasForecastAccess](https://docs.aws.amazon.com/sagemaker/latest/dg/security-iam-awsmanpol-canvas.html#security-iam-awsmanpol-AmazonSageMakerCanvasForecastAccess) policy attached and forecast.amazonaws.com added in the trust relationship as a service principal. */
    amazon_forecast_role_arn?:              any;
    /** (Optional) Describes whether the integration to the model registry is enabled or disabled in the Canvas application. Valid values are `ENABLED` and `DISABLED`. */
    status?:                                any;
    /** (Optional) The Amazon Resource Name (ARN) of the SageMaker model registry account. Required only to register model versions created by a different SageMaker Canvas AWS account than the AWS account in which SageMaker model registry is set up. */
    cross_account_model_register_role_arn?: any;
    /** (Optional) The Amazon S3 bucket used to store artifacts generated by Canvas. Updating the Amazon S3 location impacts existing configuration settings, and Canvas users no longer have access to their artifacts. Canvas users must log out and log back in to apply the new location. */
    s3_artifact_path?:                      any;
}