export interface SagemakerFeatureGroup {
    resource: Resource[];
}

export interface Resource {
    sagemaker_feature_group: SagemakerFeatureGroupClass;
}

export interface SagemakerFeatureGroupClass {
    /** (Required) The name of the Feature Group. The name must be unique within an AWS Region in an AWS account. */
    feature_group_name:             any;
    /** (Required) The name of the Feature whose value uniquely identifies a Record defined in the Feature Store. Only the latest record per identifier value will be stored in the Online Store. */
    record_identifier_feature_name: any;
    /** (Required) The name of the feature that stores the EventTime of a Record in a Feature Group. */
    event_time_feature_name:        any;
    /** (Optional) Map of resource tags for the resource. If configured with a provider [`default_tags` configuration block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) present, tags with matching keys will overwrite those defined at the provider-level. */
    tags?:                          any;
    /** (Required) The name of a feature. `feature_name` cannot be any of the following: `is_deleted`, `write_time`, `api_invocation_time`. */
    feature_name:                   any;
    /** (Required) The value type of a feature. Valid values are `Integral`, `Fractional`, or `String`. */
    feature_type:                   any;
    /** (Optional) Set to `true` to disable the automatic creation of an AWS Glue table when configuring an OfflineStore. */
    enable_online_store?:           any;
    /** (Required) The Amazon Simple Storage (Amazon S3) location of OfflineStore. See [S3 Storage Config](#s3-storage-config) Below. */
    s3_storage_config:              any;
    /** (Optional) The meta data of the Glue table that is autogenerated when an OfflineStore is created. See [Data Catalog Config](#data-catalog-config) Below. */
    data_catalog_config?:           any;
    /** (Optional) Format for the offline store table. Supported formats are `Glue` (Default) and Apache `Iceberg` (https://iceberg.apache.org/). */
    table_format?:                  any;
    /** (Optional) Set to `true` to turn Online Store On. */
    disable_glue_table_creation?:   any;
    /** (Required) Security config for at-rest encryption of your OnlineStore. See [Security Config](#security-config) Below. */
    security_config:                any;
    /** (Optional) The ID of the AWS Key Management Service (AWS KMS) key that SageMaker Feature Store uses to encrypt the Amazon S3 objects at rest using Amazon S3 server-side encryption. */
    kms_key_id?:                    any;
    /** (Required) The S3 URI, or location in Amazon S3, of OfflineStore. */
    s3_uri:                         any;
    /** (Optional) The name of the Glue table catalog. */
    catalog?:                       any;
    /** (Optional) The name of the Glue table database. */
    database?:                      any;
    /** (Optional) The name of the Glue table. */
    table_name?:                    any;
}