export interface SignerSigningProfile {
    resource: Resource[];
}

export interface Resource {
    signer_signing_profile: SignerSigningProfileClass;
}

export interface SignerSigningProfileClass {
    /** (Required) The ID of the platform that is used by the target signing profile. */
    platform_id:                any;
    /** (Optional) A unique signing profile name. By default generated by Terraform. Signing profile names are immutable and cannot be reused after canceled. */
    name?:                      any;
    /** (Optional) A signing profile name prefix. Terraform will generate a unique suffix. Conflicts with `name`. */
    name_prefix?:               any;
    /** (Optional) The validity period for a signing job. */
    signature_validity_period?: any;
    /** (Optional) A list of tags associated with the signing profile. If configured with a provider [`default_tags` configuration block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) present, tags with matching keys will overwrite those defined at the provider-level. */
    tags?:                      any;
}