export interface SignerSigningProfilePermission {
    resource: Resource[];
}

export interface Resource {
    signer_signing_profile_permission: SignerSigningProfilePermissionClass;
}

export interface SignerSigningProfilePermissionClass {
    /** (Required) Name of the signing profile to add the cross-account permissions. */
    profile_name:         any;
    /** (Required) An AWS Signer action permitted as part of cross-account permissions. Valid values: `signer:StartSigningJob`, `signer:GetSigningProfile`, or `signer:RevokeSignature`. */
    action:               any;
    /** (Required) The AWS principal to be granted a cross-account permission. */
    principal:            any;
    /** (Optional) The signing profile version that a permission applies to. */
    profile_version?:     any;
    /** (Optional) A unique statement identifier. By default generated by Terraform. */
    statement_id?:        any;
    /** (Optional) A statement identifier prefix. Terraform will generate a unique suffix. Conflicts with `statement_id`. */
    statement_id_prefix?: any;
}